project:
  type: book

book:
  title: "CPSC 330: Applied Machine Learning"
  reader-mode: true
  page-navigation: true
  favicon: "book/img/UBC-CS-logo.png"

  sidebar:
    style: floating
    collapse-level: 1
    logo: "book/img/UBC-CS-logo.png"

  navbar:
    background: "#002145"
    foreground: "#FFFFFF"

  chapters:
    - index.qmd
    - learning-objectives.qmd
    - book/01_intro.ipynb
    - part: "Foundations and Supervised Learning"
      chapters:
        - book/02_terminology-baselines-decision-trees.ipynb
        - book/03_ml-fundamentals.ipynb
        - book/04_kNNs-SVM-RBF.ipynb

    # Add the following parts when their first chapters are ready:
    # - Unsupervised Learning and Recommendation
    # - Working with Different Data Types
    # - Responsible Machine Learning in Practice

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    toc-depth: 4
    number-sections: false
    code-copy: true
    math: katex
    # anchor-sections: true
    smooth-scroll: true
    mermaid: {}
    grid:
      sidebar-width: 250px
      body-width: 960px
      margin-width: 200px
      gutter-width: 1.3em
